### ISSUE TITLE
Installing makes Trebuchet/Nova launchers crash

### ISSUE THREAD

**Issue by Johuotar** [nilesr/United4#4] opened 2017-12-12 23:36 UTC
Exactly what it says in the title. I have Galaxy S2 with Cyanogenmod 11.0. Tried to install from google play 3 times. After installation the launcher app in use will repeatedly crash. Going to settings>apps will make settings crash. Only deleting the app ends crashes.

**Comment by nilesr** [comment] 2017-12-12 23:39
That's interesting, and definitely not intended. Can you upload a crash log? I'm going to submit a bug report to cyanogenmod

**Comment by nilesr** [comment] 2017-12-12 23:40
Actually it looks like your version of cyanogenmod is 3 major releases behind.

**Comment by Johuotar** [comment] 2017-12-13 10:44
Apparently Cyanogenmod has been abandoned and has been replaced with LineageOS. I should probably see if I can update to that.

[traces_com.cyanogenmod.trebuchet.txt](https://github.com/nilesr/United4/files/1555138/traces_com.cyanogenmod.trebuchet.txt)

By crash log do you mean traces txt files?

**Comment by nilesr** [comment] 2017-12-13 16:15
No I mean like logcat logs. It looks like the file you uploaded doesn't have any reference to a crash, or to United4 (searched for uapp and burg)

**Comment by Johuotar** [comment] 2017-12-13 17:50
[LauncherLog.txt](https://github.com/nilesr/United4/files/1556442/LauncherLog.txt)
In the end of the file you can see all the services die. I assume thats what got recorded after I managed to stop trebuchet from crashing for a while by moving the icons and managed to go to the menu and attempt to start the app. It resulted in the phone restarting.

**Comment by nilesr** [comment] 2017-12-13 17:59
It's crashing in getPkgName, however I don't think that's relevant to this app. The exact error message is this

```
12-13 19:35:41.775 F/libc    ( 2215): invalid address or address of corrupt block 0x43 passed to dlfree
12-13 19:35:41.780 F/libc    ( 2215): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 4924 (Binder_F)
```

So the error message indicates that some component crashed (while de-allocating an xml tree) because either an invalid pointer was passed to free, or due to heap corruption. The code in this app is Java and does not have access to the system's heap, so it's a bug in either `libandoridfw.so` or `libc.so`, both of which are compiled C/C++ code that are part of Android itself. 

It is interesting that it crashes on `getPkgName` < `getBasePkgName` considering we've changed the package name several times, but I don't know what could be causing it. I know there have been several (some critical) updates to libxml2 since cyanogenmod 11 was released, so I think updating is probably your best bet. It's also possible the AndroidManifest xml file got corrupted when you downloaded the app, maybe you can try using 4.1.7 from the releases page and see if that fixes it.

**Comment by nilesr** [comment] 2018-06-16 19:34
It's been 6 months, closing as not reproducable

**Closed as completed by nilesr** 2018-06-16 19:34 UTC
